### ISSUE TITLE
reBuild shaders

### ISSUE THREAD

**Issue by tigrazone** [AdamYuan/VkAdypt#2]
Hello!
How to rebuild shaders with cmake/make?
Thank you

**Comment by AdamYuan** [comment]
Well, my cmake file only recompile shaders when **glslc** executable is found
On Linux, just install **glslc** shader compiler and shader/CMakeLists.txt will automatically rebuild the shaders.
On Windows, you might need to install LunarG Vulkan SDK and properly set the environment variables, so that CMake can find glslc executable.

**Comment by tigrazone** [comment]
ok, I understand.
for example, I create build folder and do cmake ..
I build executable with make.
How to rebuild shaders?
With which command and in which folder?

**Comment by AdamYuan** [comment]
just run **make** in build folder, and shaders will be recompiled if they are modified
you can also remove the shader/include/spirv folder to force recompile all the shaders

**Comment by tigrazone** [comment]
thank you!

**Comment by AdamYuan** [comment]
You're welcome :D
